# dbt/profiles/profiles.yml
mlb_pipeline:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account
      project: mlb-pipeline-deji
      dataset: staging
      threads: 4
      keyfile: /root/.dbt/gcp-key.json


